//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyclonestyle.getAvailableFlightWithPriceAndCommisionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/", ConfigurationName="getAvailableFlightWithPriceAndCommisionService.GetAvailableFlightWithPriceAndComm" +
        "isionService_1_0")]
    public interface GetAvailableFlightWithPriceAndCommisionService_1_0 {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractLiantuoReply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractLiantuoRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommisionResponse getAvailableFlightWithPriceAndCommision(cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommision request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommisionResponse> getAvailableFlightWithPriceAndCommisionAsync(cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommision request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/")]
    public partial class availableFlightWithPriceAndCommisionRequest : abstractLiantuoRequest {
        
        private string airlineCodeField;
        
        private string dateField;
        
        private string depTimeField;
        
        private string directField;
        
        private string dstAirportCodeField;
        
        private string groupField;
        
        private string officeNoField;
        
        private int onlyAvailableSeatField;
        
        private bool onlyAvailableSeatFieldSpecified;
        
        private int onlyNormalCommisionField;
        
        private bool onlyNormalCommisionFieldSpecified;
        
        private int onlyOnWorkingCommisionField;
        
        private bool onlyOnWorkingCommisionFieldSpecified;
        
        private int onlySelfPNRField;
        
        private bool onlySelfPNRFieldSpecified;
        
        private string orgAirportCodeField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private string pidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string airlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
                this.RaisePropertyChanged("airlineCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string depTime {
            get {
                return this.depTimeField;
            }
            set {
                this.depTimeField = value;
                this.RaisePropertyChanged("depTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direct {
            get {
                return this.directField;
            }
            set {
                this.directField = value;
                this.RaisePropertyChanged("direct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dstAirportCode {
            get {
                return this.dstAirportCodeField;
            }
            set {
                this.dstAirportCodeField = value;
                this.RaisePropertyChanged("dstAirportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string officeNo {
            get {
                return this.officeNoField;
            }
            set {
                this.officeNoField = value;
                this.RaisePropertyChanged("officeNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int onlyAvailableSeat {
            get {
                return this.onlyAvailableSeatField;
            }
            set {
                this.onlyAvailableSeatField = value;
                this.RaisePropertyChanged("onlyAvailableSeat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlyAvailableSeatSpecified {
            get {
                return this.onlyAvailableSeatFieldSpecified;
            }
            set {
                this.onlyAvailableSeatFieldSpecified = value;
                this.RaisePropertyChanged("onlyAvailableSeatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int onlyNormalCommision {
            get {
                return this.onlyNormalCommisionField;
            }
            set {
                this.onlyNormalCommisionField = value;
                this.RaisePropertyChanged("onlyNormalCommision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlyNormalCommisionSpecified {
            get {
                return this.onlyNormalCommisionFieldSpecified;
            }
            set {
                this.onlyNormalCommisionFieldSpecified = value;
                this.RaisePropertyChanged("onlyNormalCommisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int onlyOnWorkingCommision {
            get {
                return this.onlyOnWorkingCommisionField;
            }
            set {
                this.onlyOnWorkingCommisionField = value;
                this.RaisePropertyChanged("onlyOnWorkingCommision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlyOnWorkingCommisionSpecified {
            get {
                return this.onlyOnWorkingCommisionFieldSpecified;
            }
            set {
                this.onlyOnWorkingCommisionFieldSpecified = value;
                this.RaisePropertyChanged("onlyOnWorkingCommisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int onlySelfPNR {
            get {
                return this.onlySelfPNRField;
            }
            set {
                this.onlySelfPNRField = value;
                this.RaisePropertyChanged("onlySelfPNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlySelfPNRSpecified {
            get {
                return this.onlySelfPNRFieldSpecified;
            }
            set {
                this.onlySelfPNRFieldSpecified = value;
                this.RaisePropertyChanged("onlySelfPNRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string orgAirportCode {
            get {
                return this.orgAirportCodeField;
            }
            set {
                this.orgAirportCodeField = value;
                this.RaisePropertyChanged("orgAirportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
                this.RaisePropertyChanged("pid");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(availableFlightWithPriceAndCommisionRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/")]
    public abstract partial class abstractLiantuoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agencyCodeField;
        
        private string signField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agencyCode {
            get {
                return this.agencyCodeField;
            }
            set {
                this.agencyCodeField = value;
                this.RaisePropertyChanged("agencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("sign");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/")]
    public partial class wsPolicyData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string commentField;
        
        private double commisionMoneyField;
        
        private bool commisionMoneyFieldSpecified;
        
        private string commisionPointField;
        
        private int commisionTypeField;
        
        private bool commisionTypeFieldSpecified;
        
        private int needSwitchPNRField;
        
        private bool needSwitchPNRFieldSpecified;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private int policyBelongToField;
        
        private bool policyBelongToFieldSpecified;
        
        private int policyIdField;
        
        private bool policyIdFieldSpecified;
        
        private string policyTypeField;
        
        private int seatTypeField;
        
        private bool seatTypeFieldSpecified;
        
        private string vtWorkTimeField;
        
        private string workTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double commisionMoney {
            get {
                return this.commisionMoneyField;
            }
            set {
                this.commisionMoneyField = value;
                this.RaisePropertyChanged("commisionMoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commisionMoneySpecified {
            get {
                return this.commisionMoneyFieldSpecified;
            }
            set {
                this.commisionMoneyFieldSpecified = value;
                this.RaisePropertyChanged("commisionMoneySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string commisionPoint {
            get {
                return this.commisionPointField;
            }
            set {
                this.commisionPointField = value;
                this.RaisePropertyChanged("commisionPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int commisionType {
            get {
                return this.commisionTypeField;
            }
            set {
                this.commisionTypeField = value;
                this.RaisePropertyChanged("commisionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commisionTypeSpecified {
            get {
                return this.commisionTypeFieldSpecified;
            }
            set {
                this.commisionTypeFieldSpecified = value;
                this.RaisePropertyChanged("commisionTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int needSwitchPNR {
            get {
                return this.needSwitchPNRField;
            }
            set {
                this.needSwitchPNRField = value;
                this.RaisePropertyChanged("needSwitchPNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSwitchPNRSpecified {
            get {
                return this.needSwitchPNRFieldSpecified;
            }
            set {
                this.needSwitchPNRFieldSpecified = value;
                this.RaisePropertyChanged("needSwitchPNRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int policyBelongTo {
            get {
                return this.policyBelongToField;
            }
            set {
                this.policyBelongToField = value;
                this.RaisePropertyChanged("policyBelongTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool policyBelongToSpecified {
            get {
                return this.policyBelongToFieldSpecified;
            }
            set {
                this.policyBelongToFieldSpecified = value;
                this.RaisePropertyChanged("policyBelongToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int policyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
                this.RaisePropertyChanged("policyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool policyIdSpecified {
            get {
                return this.policyIdFieldSpecified;
            }
            set {
                this.policyIdFieldSpecified = value;
                this.RaisePropertyChanged("policyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string policyType {
            get {
                return this.policyTypeField;
            }
            set {
                this.policyTypeField = value;
                this.RaisePropertyChanged("policyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int seatType {
            get {
                return this.seatTypeField;
            }
            set {
                this.seatTypeField = value;
                this.RaisePropertyChanged("seatType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatTypeSpecified {
            get {
                return this.seatTypeFieldSpecified;
            }
            set {
                this.seatTypeFieldSpecified = value;
                this.RaisePropertyChanged("seatTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string vtWorkTime {
            get {
                return this.vtWorkTimeField;
            }
            set {
                this.vtWorkTimeField = value;
                this.RaisePropertyChanged("vtWorkTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string workTime {
            get {
                return this.workTimeField;
            }
            set {
                this.workTimeField = value;
                this.RaisePropertyChanged("workTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/")]
    public partial class wsSeatWithPriceAndComisionItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double discountField;
        
        private bool discountFieldSpecified;
        
        private string flightNoField;
        
        private int parPriceField;
        
        private bool parPriceFieldSpecified;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private wsPolicyData policyDataField;
        
        private string seatCodeField;
        
        private string seatMsgField;
        
        private string seatStatusField;
        
        private int seatTypeField;
        
        private bool seatTypeFieldSpecified;
        
        private double settlePriceField;
        
        private bool settlePriceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
                this.RaisePropertyChanged("discount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountSpecified {
            get {
                return this.discountFieldSpecified;
            }
            set {
                this.discountFieldSpecified = value;
                this.RaisePropertyChanged("discountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string flightNo {
            get {
                return this.flightNoField;
            }
            set {
                this.flightNoField = value;
                this.RaisePropertyChanged("flightNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int parPrice {
            get {
                return this.parPriceField;
            }
            set {
                this.parPriceField = value;
                this.RaisePropertyChanged("parPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parPriceSpecified {
            get {
                return this.parPriceFieldSpecified;
            }
            set {
                this.parPriceFieldSpecified = value;
                this.RaisePropertyChanged("parPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public wsPolicyData policyData {
            get {
                return this.policyDataField;
            }
            set {
                this.policyDataField = value;
                this.RaisePropertyChanged("policyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string seatCode {
            get {
                return this.seatCodeField;
            }
            set {
                this.seatCodeField = value;
                this.RaisePropertyChanged("seatCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string seatMsg {
            get {
                return this.seatMsgField;
            }
            set {
                this.seatMsgField = value;
                this.RaisePropertyChanged("seatMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string seatStatus {
            get {
                return this.seatStatusField;
            }
            set {
                this.seatStatusField = value;
                this.RaisePropertyChanged("seatStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int seatType {
            get {
                return this.seatTypeField;
            }
            set {
                this.seatTypeField = value;
                this.RaisePropertyChanged("seatType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatTypeSpecified {
            get {
                return this.seatTypeFieldSpecified;
            }
            set {
                this.seatTypeFieldSpecified = value;
                this.RaisePropertyChanged("seatTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double settlePrice {
            get {
                return this.settlePriceField;
            }
            set {
                this.settlePriceField = value;
                this.RaisePropertyChanged("settlePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool settlePriceSpecified {
            get {
                return this.settlePriceFieldSpecified;
            }
            set {
                this.settlePriceFieldSpecified = value;
                this.RaisePropertyChanged("settlePriceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/")]
    public partial class wsFlightWithPriceAndCommision : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double airportTaxField;
        
        private bool airportTaxFieldSpecified;
        
        private string arriModifyTimeField;
        
        private string arriTimeField;
        
        private bool codeShareField;
        
        private bool codeShareFieldSpecified;
        
        private string depModifyTimeField;
        
        private string depTimeField;
        
        private string dstCityField;
        
        private string dstJetquayField;
        
        private string flightNoField;
        
        private double fuelTaxField;
        
        private bool fuelTaxFieldSpecified;
        
        private bool isElectronicTicketField;
        
        private bool isElectronicTicketFieldSpecified;
        
        private string linkField;
        
        private string mealField;
        
        private string orgCityField;
        
        private string orgJetquayField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private string planeTypeField;
        
        private wsSeatWithPriceAndComisionItem[] seatItemsField;
        
        private string shareNumField;
        
        private int stopnumField;
        
        private bool stopnumFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double airportTax {
            get {
                return this.airportTaxField;
            }
            set {
                this.airportTaxField = value;
                this.RaisePropertyChanged("airportTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool airportTaxSpecified {
            get {
                return this.airportTaxFieldSpecified;
            }
            set {
                this.airportTaxFieldSpecified = value;
                this.RaisePropertyChanged("airportTaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arriModifyTime {
            get {
                return this.arriModifyTimeField;
            }
            set {
                this.arriModifyTimeField = value;
                this.RaisePropertyChanged("arriModifyTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arriTime {
            get {
                return this.arriTimeField;
            }
            set {
                this.arriTimeField = value;
                this.RaisePropertyChanged("arriTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool codeShare {
            get {
                return this.codeShareField;
            }
            set {
                this.codeShareField = value;
                this.RaisePropertyChanged("codeShare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeShareSpecified {
            get {
                return this.codeShareFieldSpecified;
            }
            set {
                this.codeShareFieldSpecified = value;
                this.RaisePropertyChanged("codeShareSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string depModifyTime {
            get {
                return this.depModifyTimeField;
            }
            set {
                this.depModifyTimeField = value;
                this.RaisePropertyChanged("depModifyTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string depTime {
            get {
                return this.depTimeField;
            }
            set {
                this.depTimeField = value;
                this.RaisePropertyChanged("depTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string dstCity {
            get {
                return this.dstCityField;
            }
            set {
                this.dstCityField = value;
                this.RaisePropertyChanged("dstCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dstJetquay {
            get {
                return this.dstJetquayField;
            }
            set {
                this.dstJetquayField = value;
                this.RaisePropertyChanged("dstJetquay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string flightNo {
            get {
                return this.flightNoField;
            }
            set {
                this.flightNoField = value;
                this.RaisePropertyChanged("flightNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double fuelTax {
            get {
                return this.fuelTaxField;
            }
            set {
                this.fuelTaxField = value;
                this.RaisePropertyChanged("fuelTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuelTaxSpecified {
            get {
                return this.fuelTaxFieldSpecified;
            }
            set {
                this.fuelTaxFieldSpecified = value;
                this.RaisePropertyChanged("fuelTaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool isElectronicTicket {
            get {
                return this.isElectronicTicketField;
            }
            set {
                this.isElectronicTicketField = value;
                this.RaisePropertyChanged("isElectronicTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isElectronicTicketSpecified {
            get {
                return this.isElectronicTicketFieldSpecified;
            }
            set {
                this.isElectronicTicketFieldSpecified = value;
                this.RaisePropertyChanged("isElectronicTicketSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string meal {
            get {
                return this.mealField;
            }
            set {
                this.mealField = value;
                this.RaisePropertyChanged("meal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string orgCity {
            get {
                return this.orgCityField;
            }
            set {
                this.orgCityField = value;
                this.RaisePropertyChanged("orgCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string orgJetquay {
            get {
                return this.orgJetquayField;
            }
            set {
                this.orgJetquayField = value;
                this.RaisePropertyChanged("orgJetquay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string planeType {
            get {
                return this.planeTypeField;
            }
            set {
                this.planeTypeField = value;
                this.RaisePropertyChanged("planeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seatItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public wsSeatWithPriceAndComisionItem[] seatItems {
            get {
                return this.seatItemsField;
            }
            set {
                this.seatItemsField = value;
                this.RaisePropertyChanged("seatItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string shareNum {
            get {
                return this.shareNumField;
            }
            set {
                this.shareNumField = value;
                this.RaisePropertyChanged("shareNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int stopnum {
            get {
                return this.stopnumField;
            }
            set {
                this.stopnumField = value;
                this.RaisePropertyChanged("stopnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stopnumSpecified {
            get {
                return this.stopnumFieldSpecified;
            }
            set {
                this.stopnumFieldSpecified = value;
                this.RaisePropertyChanged("stopnumSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/")]
    public partial class wsFlightWithPriceAndCommisionItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double audletAirportTaxField;
        
        private bool audletAirportTaxFieldSpecified;
        
        private double audletFuelTaxField;
        
        private bool audletFuelTaxFieldSpecified;
        
        private double basePriceField;
        
        private bool basePriceFieldSpecified;
        
        private string dateField;
        
        private double distanceField;
        
        private bool distanceFieldSpecified;
        
        private string dstCityField;
        
        private wsFlightWithPriceAndCommision[] flightsField;
        
        private string orgCityField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double audletAirportTax {
            get {
                return this.audletAirportTaxField;
            }
            set {
                this.audletAirportTaxField = value;
                this.RaisePropertyChanged("audletAirportTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool audletAirportTaxSpecified {
            get {
                return this.audletAirportTaxFieldSpecified;
            }
            set {
                this.audletAirportTaxFieldSpecified = value;
                this.RaisePropertyChanged("audletAirportTaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double audletFuelTax {
            get {
                return this.audletFuelTaxField;
            }
            set {
                this.audletFuelTaxField = value;
                this.RaisePropertyChanged("audletFuelTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool audletFuelTaxSpecified {
            get {
                return this.audletFuelTaxFieldSpecified;
            }
            set {
                this.audletFuelTaxFieldSpecified = value;
                this.RaisePropertyChanged("audletFuelTaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double basePrice {
            get {
                return this.basePriceField;
            }
            set {
                this.basePriceField = value;
                this.RaisePropertyChanged("basePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool basePriceSpecified {
            get {
                return this.basePriceFieldSpecified;
            }
            set {
                this.basePriceFieldSpecified = value;
                this.RaisePropertyChanged("basePriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distanceSpecified {
            get {
                return this.distanceFieldSpecified;
            }
            set {
                this.distanceFieldSpecified = value;
                this.RaisePropertyChanged("distanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dstCity {
            get {
                return this.dstCityField;
            }
            set {
                this.dstCityField = value;
                this.RaisePropertyChanged("dstCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flights", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public wsFlightWithPriceAndCommision[] flights {
            get {
                return this.flightsField;
            }
            set {
                this.flightsField = value;
                this.RaisePropertyChanged("flights");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string orgCity {
            get {
                return this.orgCityField;
            }
            set {
                this.orgCityField = value;
                this.RaisePropertyChanged("orgCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(availableFlightWithPriceAndCommisionReply))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/")]
    public abstract partial class abstractLiantuoReply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string returnStackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("returnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string returnStackTrace {
            get {
                return this.returnStackTraceField;
            }
            set {
                this.returnStackTraceField = value;
                this.RaisePropertyChanged("returnStackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/")]
    public partial class availableFlightWithPriceAndCommisionReply : abstractLiantuoReply {
        
        private wsFlightWithPriceAndCommisionItem[] flightItemsField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flightItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public wsFlightWithPriceAndCommisionItem[] flightItems {
            get {
                return this.flightItemsField;
            }
            set {
                this.flightItemsField = value;
                this.RaisePropertyChanged("flightItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAvailableFlightWithPriceAndCommision", WrapperNamespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/", IsWrapped=true)]
    public partial class getAvailableFlightWithPriceAndCommision {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
            "model.ltips.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cyclonestyle.getAvailableFlightWithPriceAndCommisionService.availableFlightWithPriceAndCommisionRequest request;
        
        public getAvailableFlightWithPriceAndCommision() {
        }
        
        public getAvailableFlightWithPriceAndCommision(cyclonestyle.getAvailableFlightWithPriceAndCommisionService.availableFlightWithPriceAndCommisionRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAvailableFlightWithPriceAndCommisionResponse", WrapperNamespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
        "model.ltips.com/", IsWrapped=true)]
    public partial class getAvailableFlightWithPriceAndCommisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://getavailableflightwithpriceandcommision.b2b.service.version1_0.webservice." +
            "model.ltips.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cyclonestyle.getAvailableFlightWithPriceAndCommisionService.availableFlightWithPriceAndCommisionReply @return;
        
        public getAvailableFlightWithPriceAndCommisionResponse() {
        }
        
        public getAvailableFlightWithPriceAndCommisionResponse(cyclonestyle.getAvailableFlightWithPriceAndCommisionService.availableFlightWithPriceAndCommisionReply @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetAvailableFlightWithPriceAndCommisionService_1_0Channel : cyclonestyle.getAvailableFlightWithPriceAndCommisionService.GetAvailableFlightWithPriceAndCommisionService_1_0, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAvailableFlightWithPriceAndCommisionService_1_0Client : System.ServiceModel.ClientBase<cyclonestyle.getAvailableFlightWithPriceAndCommisionService.GetAvailableFlightWithPriceAndCommisionService_1_0>, cyclonestyle.getAvailableFlightWithPriceAndCommisionService.GetAvailableFlightWithPriceAndCommisionService_1_0 {
        
        public GetAvailableFlightWithPriceAndCommisionService_1_0Client() {
        }
        
        public GetAvailableFlightWithPriceAndCommisionService_1_0Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetAvailableFlightWithPriceAndCommisionService_1_0Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAvailableFlightWithPriceAndCommisionService_1_0Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAvailableFlightWithPriceAndCommisionService_1_0Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommisionResponse cyclonestyle.getAvailableFlightWithPriceAndCommisionService.GetAvailableFlightWithPriceAndCommisionService_1_0.getAvailableFlightWithPriceAndCommision(cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommision request) {
            return base.Channel.getAvailableFlightWithPriceAndCommision(request);
        }
        
        public cyclonestyle.getAvailableFlightWithPriceAndCommisionService.availableFlightWithPriceAndCommisionReply getAvailableFlightWithPriceAndCommision(cyclonestyle.getAvailableFlightWithPriceAndCommisionService.availableFlightWithPriceAndCommisionRequest request) {
            cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommision inValue = new cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommision();
            inValue.request = request;
            cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommisionResponse retVal = ((cyclonestyle.getAvailableFlightWithPriceAndCommisionService.GetAvailableFlightWithPriceAndCommisionService_1_0)(this)).getAvailableFlightWithPriceAndCommision(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommisionResponse> cyclonestyle.getAvailableFlightWithPriceAndCommisionService.GetAvailableFlightWithPriceAndCommisionService_1_0.getAvailableFlightWithPriceAndCommisionAsync(cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommision request) {
            return base.Channel.getAvailableFlightWithPriceAndCommisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommisionResponse> getAvailableFlightWithPriceAndCommisionAsync(cyclonestyle.getAvailableFlightWithPriceAndCommisionService.availableFlightWithPriceAndCommisionRequest request) {
            cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommision inValue = new cyclonestyle.getAvailableFlightWithPriceAndCommisionService.getAvailableFlightWithPriceAndCommision();
            inValue.request = request;
            return ((cyclonestyle.getAvailableFlightWithPriceAndCommisionService.GetAvailableFlightWithPriceAndCommisionService_1_0)(this)).getAvailableFlightWithPriceAndCommisionAsync(inValue);
        }
    }
}
